### ISSUE TITLE
Add filtering option

### ISSUE THREAD

**Issue by richard-still-ft** [Financial-Times/next-ft-api-client#20]
Return a list of IDs, sorted by date and filtered by some arbitrary metadata. The ES query will look a bit like this:

POST https://elasticSearch/v1_api_v2/item/_search

    {
		"fields" : [], // using an empty array will return just the ES stuff
		"from" : 0,
		"size" : 50,
		"query": { // Filtered to Comment
			"filtered": {
				"filter": {
					"term": {
						"item.metadata.genre.term.name": "Comment"
					}
				}
			}
		},
	    "sort": [ // Sorted by date 
	        {
	            "item.lifecycle.lastPublishDateTime": {
	                "order": "desc"
	            }
	        }
	    ]
	}

**Comment by matthew-andrews** [comment]
how does one do “OR” searches?
