### ISSUE TITLE
Filters not queries

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-ft-api-client#51]
From elasticsearch docs:
> As a general rule, queries should be used instead of filters:
> for full text search
> where the result depends on a relevance score

We're almost exclusively using queries even though very few of them meet the above criteria. Should we move over to filters? (Clue: the answer's yes)

**Comment by i-like-robots** [comment]
Caveat: This query is legit https://github.com/Financial-Times/next-ft-api-client/blob/master/src/related-tags.js#L45-L58

**Comment by wheresrhys** [comment]
This has been done now hasn't it? @i-like-robots

**Comment by i-like-robots** [comment]
Not quite! I've re-written the related tags to be a filtered aggregation against the V3 index. Will try to benchmark it too.

**Comment by i-like-robots** [comment]
And ES v1 index is still query but that's going to deprecated https://github.com/Financial-Times/next-ft-api-client/blob/master/src/search-legacy.js

For comparison ES v3 search _is_ based on filters https://github.com/Financial-Times/next-ft-api-client/blob/master/src/search.js
